spring:
  data:
    redis:
      port: 6379 # Redis 服务器端口
      host: 127.0.0.1  # Redis 服务器地址
      database: 0 # Redis 服务器索引 默认为0
      password: # Redis 服务器密码（默认为0）
      lettuce:
        pool:
          min-idle: 10 # 连接池中的最小空闲数，默认为0
          max-idle: 20 # 连接池中的最大空闲数，默认为0
          max-active: 100 #连接池的最大连接数，默认为0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 20040502



  mvc:
    hiddenmethod:
      filter:
        enabled=false

zxk:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c8cd4da0a018f2435a31d7585
      accountToken: c649a07ec2ba4275a57ec672b5b47970
      appId: 2c94811c8cd4da0a018f2435a4a5758c
      templateId: 1
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为0)

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
      api-docs:
        path: /v3/api-docs
      group-configs:
        -group: 'default'
        paths-to-match: '/**'
        packages-to-scan: top.zxk.springboot.redis.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

